### ISSUE TITLE
tagbox: Add option maxTags

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#1]
Add a new option maxTags to confine the number of tags.

**Comment by yamass** [comment]
Good feature request.

However, here's a question: How should the user be notified of reaching the limit?

First implementation: No feedback. Will be changed as soon as we have a consensus on the behavior.

**Comment by larmic** [comment]
For my usage no feedback will do the job. Maybe setting a certain style class to allow custom feedback?

**Comment by larmic** [comment]
Works fine on master. thx alot
