### ISSUE TITLE
Tree: using showSearchField allows free text search

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#13]
When using showSearchField no input field for tree filter search is shown but searching is allowed. Filtering should be disabled in this case. Otherwise if you enter a string that does not exist tree model no tree will be rendered.

**Comment by yamass** [comment]
Please check and close.

**Comment by yamass** [comment]
By the way: 

I removed the old flag "showSearchField" and replaced it with **searchBarMode**.

Possible values: 
* none
* show-if-filled
* always-visible

**Comment by larmic** [comment]
Works!
