### ISSUE TITLE
tagbox: Add option maxChars

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#2]
Add a new option maxChars to confine the number of letters.

**Comment by yamass** [comment]
@larmic What kind of feedback would you like to see here. 

I am not sure if I would like to add this as a feature. If I add a popover or any other kind of validation message, it will potentially break other people's error message designs.

Maybe you should consider adding a change listener to the tagbox and doing the needed validation stuff yourself.

**Comment by larmic** [comment]
You are right. A change listener will do this as well.
