### ISSUE TITLE
TrivialTreeComboBox: Add emptyEntryTemplate for non selected entries as an additional option

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#27]
Up to now there is no way to add a custom template for unselected entry. 

Use custom selectedEntryTemplate with emptyEntry is not fine when template contains static content. 

Example
![butterfaces__a_lightweight_and_modern_jsf_framework](https://cloud.githubusercontent.com/assets/1371298/12092046/0dad8cbe-b2fb-11e5-8c19-ca14562cf66d.png)
with 
```
<div class="editor-area">
   <strong>{{title}}</strong>
   <div>Created: {{createDate}}</div>
   <div>UUID: {{uuid}}</div>
</div>
```
as template.

**Comment by yamass** [comment]
Already fixed in january... see #30 .
