### ISSUE TITLE
TrivialTreeComboBox: Wrapper class editor-area seems to be needed when using custom template

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#28]
When using 
```
<strong>{{title}}</strong>
<div>Created: {{createDate}}</div>
<div>UUID: {{uuid}}</div>
```
as template for TrivialTreeComboBox a javascript error occurs
```
Uncaught TypeError: Cannot read property 'nodeType' of undefined
```

but when using 
```
<div class="editor-area">
   <strong>{{title}}</strong>
   <div>Created: {{createDate}}</div>
   <div>UUID: {{uuid}}</div>
</div>
```
everything is fine.

**Comment by larmic** [comment]
Ok,

I understand the function of editor-area. I would prefer it it your components add editor-area by themself if no editor-area class exists in given template.

**Comment by larmic** [comment]
It is kind of confusing that you have to specify editor-area in a selectedEntryTemplate. In my opinion the editing part should have a specific template (like editorTemplate). I'm more flexible if I can configure a specific template for editing instead of having an editor-area in a template that should render the selected entity.

**Comment by yamass** [comment]
As discussed via live chat: I will make specifying editor-area optional. If not specified, the editor will fall back to filling the whole template. I'm not yet sure if I want to have a special editing template. Let me think about that. I you insist on that, please open a new ticket.
