### ISSUE TITLE
TrivialTreeComboBox: Add additional list support

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#29]
TrivialTreeComboBox and TrivialComboBox does not behave similar.

Maybe it is better to support just one component (TrivialTreeComboBox) and when entries are a list instead of a tree just remove the tr-tree-expander?

**Comment by yamass** [comment]
Please, could you be more precise about the kind of mismatches in behaviour?

**Comment by larmic** [comment]
I think this was a mistake by myself. TrivialTreeComboBox and TrivialComboBox have different attributes (like template and templates). That was confusing me.
