### ISSUE TITLE
Improvement: Add option readonly

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#3]
Add a non writeable version that only displays selectedEntries but does not allow editing.

**Comment by yamass** [comment]
I am considering to add some sort of generic readonly component for entries. Just a very primitive entry renderer with a fiew style options.

@larmic Would that be ok?

By the way: I'll open another issue for a "disabled" option.

**Comment by larmic** [comment]
I think readonly should only render tags without surrounding input box. Disabled should render a disabled input field as well. Are you going with that?

**Comment by yamass** [comment]
I added both in commit 8dd89d8b1a5ce87bbf25edff0138720a81885017. (It was quite straight forward to do both at the same time, so I did not open another issue for the disabled option).

The config property is called "editingMode" and can have one of the following values: "editable", "disabled", "readonly".
