### ISSUE TITLE
Add a kind of correlation id between input wrappers and their drop down elements

### ISSUE THREAD

**Issue by szerhusenBC** [trivial-components/trivial-components#32]
I have to reopen the discussion about a kind of correlation id between the input wrappers and their drop down elements.

This discussion based on an earlier discussion you can find under https://github.com/trivial-components/trivial-components/issues/31.

In Butterfaces (JSF) we have the following problem:

Let's take the simplified HTML for understanding the problem:

```xml
<body>
   <div id="rerenderArea>
      <input class="tr-input-wrapper" />
   </div>
   <div class="tr-dropdown">the drop down element ...</div>
</body>
```

If we now rerender the area #rerenderArea this area will be emptied and replaced with the updated content by JSF. Now we have the problem that the generated drop down element will not be deleted and stays in the DOM tree without a corresponding input element. Because of this we have many orphaned drop down elements in the DOM tree if we do JSF rerenderings.

As mentioned in the earlier discussion there is a "destroy" function that can be called on a trivial component that would delete the drop down element as well, but this does not help in JSF because we don't have the component (js) objects stored. To use the destroy functions we would have to implement an interceptor für the JSF JS API that determines all trivial components in the areas, that will be rerendered, and call their destroy methods before JSF does it's work. That would be too complicated!

So we need a possibility to determine orphaned drop down elements by a correlation id.

My idea:

* Put a data attribute on the input wrapper like data-tr-id='someId'
* Put a data attribute on the drop down element like data-tr-for='someId'

```xml
<body>
   <div id="rerenderArea>
      <input class="tr-input-wrapper" data-tr-id="someId"/>
   </div>
   <div class="tr-dropdown" data-tr-for="someId">the drop down element ...</div>
</body>
```

So we can determine drop down elements that doesn't have a corresponding input element anymore. Furthermore I think that this attribute doesn't hurt, even If other people don't it.

**Comment by yamass** [comment]
There might be two alternative ways to get around your problem:

# An API method for getting the dropdown element. You could by that means add every kind of attributes (especially correlation IDs) that you ever need.
# An option for specifying the dropdown container (maybe `dropDownContainer`). This would work analogous to the Twitter Bootstrap popover's `container` option.

What do you think? Would this help you?

**Comment by szerhusenBC** [comment]
The first alternative would be great for us, so we could add any attributes on the wrapper and drop down container ourselves.

**Comment by yamass** [comment]
Please check and close this issue.

**Comment by larmic** [comment]
Works fine. Can be closed!
