### ISSUE TITLE
(Tree-)Combobox: A previous selected value can't be deleted anymore

### ISSUE THREAD

**Issue by szerhusenBC** [trivial-components/trivial-components#33]
In the actual version it is not possible do delete a previous selected value. Everytime I delete the value in the editor, blur the field, press Return or Tab afterwards, the previous selected value is shown again.

In the showcase it is still possible. I guess there is an older version online.

**Comment by yamass** [comment]
I cannot find the corresponding commits on the butterfaces fork anymore. I will therefore commit my own fix. Quite much the same as the proposed fix, except considering more corner cases.

@szerhusenBC Anyway, thank you and sorry for taking so long to react on your pull request!!
