### ISSUE TITLE
List, Combobox: inputTextProperty isn't set as value if valueProperty is not configured

### ISSUE THREAD

**Issue by szerhusenBC** [trivial-components/trivial-components#35]
At the components List and Combobox the inputTextProperty should be taken as valueProperty if valueProperty is not given. Per default the value "displayValue" should be taken for inputTextProperty.

The problem at both components is, that if valueProperty is not set and you select an entry like

```
selectedEntry {
  id: 4711,
  displayValue: 'myValue',
  foo: 'bar'
}
```

nothing is set in the original input field. I would expect 'myValue' to be set in this case.

**Comment by yamass** [comment]
The latest refactoring significantly changed the API. I will further replace the `valueProperty` configuration parameter by a function `valueFunction(entry) => string`.

I will notify you when I'm done (not sure when exactly I will do the change, might be in a few weeks only...).

**Comment by yamass** [comment]
Closing this issue ;-) Changes have been communicated via email/telephone.
