### ISSUE TITLE
Improvement treeCombobox: Remove selected entry with mouse click

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#39]
For some of our application users it is not clear how to remove a selected entry from a treeCombobox. Is it possible to add a simple x (or something like that) that removes selected value?

**Comment by yamass** [comment]
Approved. Some other user wants this too ;-)

**Comment by yamass** [comment]
Hey @larmic,

I finally implemented this. Please check and close.

Beware that there have been a few major API changes in the last days. For questions, feel free to contact me.

**Comment by larmic** [comment]
Seems to work fine. Thanks!
