### ISSUE TITLE
tagbox: Remove dropdown if no selectable entries exist

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#4]
Sometimes no selectable entries are needed. In this case no dropdown should appear.

**Comment by yamass** [comment]
Ok, I will prevent the dropdown from appearing if you don't specify either of `entries` and `queryFunction`.

**Comment by yamass** [comment]
As this is very tagbox specific, I will add it only there.

**Comment by larmic** [comment]
Works fine on master
