### ISSUE TITLE
tagbox: AllowFreeText does not work properly

### ISSUE THREAD

**Issue by larmic** [trivial-components/trivial-components#5]
I'm not able to use

```
$('#someId').TrivialTagBox({
autoComplete: false,
allowFreeText: true,
valueProperty: displayValue,
template: TrivialComponents.singleLineTemplate
});")
```
In this case duplicated entries will not work.

**Comment by yamass** [comment]
@larmic What do you mean by "will not work"? Are you experiencing this with the current master commit?

**Comment by larmic** [comment]
When I'm using upper code I was only able to enter one word. AllowFreeText does not help.

**Comment by larmic** [comment]
Seems to work now.
